### ISSUE TITLE
When should Contractors appear?

### ISSUE THREAD

**Issue by vitalii2011** [Royal-Modding/FS19_CallContractors#9]
I don't have any after saving either. Switching the field selection is not active, "1" and "dark buttons" with arrows.

**Comment by vitalii2011** [comment]
P.S. The question is removed: I checked on a field with a purchased plot without a field, so a "non-functioning" window appeared, and not the message: "There's nothing for you here, buy some land first!". 

But there was another question: On the vanilla map(Ravenport), with a purchased plot with a field(21) of ripe wheat in the types of work ("Job"), there is no"Selling".

**Comment by TyKonKet** [comment]
@vitalii2011 
Selling appear only if you have a silo and something to sell in that silo.

**Comment by vitalii2011** [comment]
> 
> 
> @vitalii2011
> Selling appear only if you have a silo and something to sell in that silo.
On the same map(Ravenport), I bought a different field with a ripe wheat and was the item "Selling". There was nothing more bought, the silo, etc. Money for sale, nevertheless came, but the wheat remained in the field.

**Comment by TyKonKet** [comment]
Selling is for selling goods stored in the silo, not to harvest a field.

**Comment by vitalii2011** [comment]
What did I sell? This was the "New Farmer" level, in which nothing seems to be given out except money.

**Comment by TyKonKet** [comment]
Harvesting contracts will be implemented in the future.

**Comment by vitalii2011** [comment]
> 
> 
> Harvesting contracts will be implemented in the future.

Excellent. 
Did I add some minor corrections to the Russian translation so that the text would fit in the window cells?
        <text name="cc_job_type_subsoiling"                         text="Чизелевание" />
        <text name="cc_job_type_limeSpreading"                      text="Известкован." />

**Comment by TyKonKet** [comment]
Done 👍🏻

**Comment by vitalii2011** [comment]
Grazie mille.
